# Generated by Django 3.1.4 on 2020-12-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Data',
            new_name='Visit_data',
        ),
    ]
