# Generated by Django 3.1.4 on 2020-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201207_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=15, null=True)),
                ('Visit_data', models.DateTimeField(null=True)),
                ('Visit_status', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='Visit_data',
        ),
        migrations.RemoveField(
            model_name='information',
            name='Visit_status',
        ),
    ]
